name: Deploy Laravel on AWS

on:
  workflow_dispatch:
    inputs:
      reName:
        description: 'Enter the directory name for the Laravel application'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" | tr -d '\r' > ssh_key.pem
          sudo chmod 600 ssh_key.pem  # Set the right permissions for the key file

      - name: Deploy to AWS EC2
        env:
          SERVER_IP: "13.215.232.150"
          NEW_DIR_NAME: ${{ github.event.inputs.reName }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DB: "laravel"
          MYSQL_USER: "action"
          MYSQL_USER_PASSWORD: ${{ secrets.MYSQL_USER_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$SERVER_IP << EOF
            # Update and install MySQL server
            sudo apt update
            sudo apt install -y mysql-server

            # Configure MySQL for remote access
            sudo sed -i "s/bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
            sudo systemctl restart mysql

            # Set up MySQL root password and create database and user
            sudo mysql -u root <<EOSQL
              ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '$MYSQL_ROOT_PASSWORD';
              FLUSH PRIVILEGES;
              CREATE DATABASE IF NOT EXISTS $MYSQL_DB;
              CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PASSWORD';
              GRANT ALL PRIVILEGES ON $MYSQL_DB.* TO '$MYSQL_USER'@'%';
              FLUSH PRIVILEGES;
            EOSQL

            # Clone the repository
            cd /var/www
            sudo rm -rf $NEW_DIR_NAME  # Remove existing directory if it exists
            sudo git clone https://github.com/007LUNA/laravel-action.git $NEW_DIR_NAME
            
            # Move into the cloned directory
            cd $NEW_DIR_NAME
            sudo git checkout main

            # Set up Laravel environment
            sudo cp .env.example .env
            sudo sed -i "s/DB_HOST=.*/DB_HOST=127.0.0.1/" .env
            sudo sed -i "s/DB_DATABASE=.*/DB_DATABASE=$MYSQL_DB/" .env
            sudo sed -i "s/DB_USERNAME=.*/DB_USERNAME=$MYSQL_USER/" .env
            sudo sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=$MYSQL_USER_PASSWORD/" .env

            # Install dependencies and optimize Laravel
            sudo apt install -y composer
            sudo composer install --optimize-autoloader --no-dev
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            php artisan key:generate
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
          EOF

      - name: Clean up SSH key
        run: rm ssh_key.pem  # Remove the SSH key file after the job completes
